In [1]:
import numpy as np

- 1부터 50 까지 짝수만 원소로 갖는 넘파이 배열 생성

In [4]:
arr1 = np.arange(2,50,2)
arr1

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
       36, 38, 40, 42, 44, 46, 48])

- 1. 0으로 채워진 4x4 배열
- 2. 1로 채원진 10x10 배열

In [10]:
arr2= np.zeros((4,4))
arr2

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
arr3= np.ones((10,10))
arr3

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [12]:
arr4= np.full((7,4),4)
arr4

array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

- 1부터 100까지 원소 중 3의 배수를 원소로 갖는 넘파이 배열생성

In [13]:
arr5 = np.arange(3,101,3)
arr5

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51,
       54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

 - 만들어진 3의 배수를 원소로 갖는 넘파이 배열의 (원소) 개수를 구하고, reshape함수를 이용하여 2차원 배열을 생성
 - 생성된 2 차원의 배열의 크기를 구하기


In [14]:
arr5.size

33

In [19]:
re = arr5.reshape((11,3))                
re

array([[ 3,  6,  9],
       [12, 15, 18],
       [21, 24, 27],
       [30, 33, 36],
       [39, 42, 45],
       [48, 51, 54],
       [57, 60, 63],
       [66, 69, 72],
       [75, 78, 81],
       [84, 87, 90],
       [93, 96, 99]])

In [20]:
print(re.shape)

(11, 3)


- 0~1사이의 값을 랜덤하게 가지는 6*4 배열을 생성
- 1~100 사이의 값ㅇ르 랜덤하게 가지는 5*5 배열을 생성
- astype을 사용하여 2번의 배열을 실수형태의 원소를 가지는 배열로 바꾸기

In [21]:
import random

In [30]:
arr6 = np.random.rand(6,4) 
arr6

array([[0.56672274, 0.59116254, 0.51646744, 0.79399032],
       [0.61093246, 0.53865516, 0.50749844, 0.15686694],
       [0.34224831, 0.85752389, 0.83440841, 0.30121685],
       [0.70367118, 0.92080224, 0.69475322, 0.29046594],
       [0.22154816, 0.18520394, 0.92747647, 0.35167924],
       [0.36840257, 0.2516835 , 0.66990886, 0.98510573]])

In [33]:
arr7 = np.random.randint(1,100, size = (5,5))
arr7

array([[29, 98, 12,  3, 43],
       [46, 42, 10,  8, 14],
       [63, 58, 63, 35, 50],
       [ 7, 58, 15, 41, 73],
       [68, 33,  4, 19, 72]])

In [34]:
arr_type = arr7.astype("float64")                             
arr_type

array([[29., 98., 12.,  3., 43.],
       [46., 42., 10.,  8., 14.],
       [63., 58., 63., 35., 50.],
       [ 7., 58., 15., 41., 73.],
       [68., 33.,  4., 19., 72.]])

- 주어진 배열에서 3,4,8,9 원소만 가져오기
- 주어진 배열에서 6,7,8 만 가져오기

  x = np.arange(10).reshape(2,5)

In [35]:
x = np.arange(10).reshape(2,5)
print(x)

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [40]:
x[:,3:]

array([[3, 4],
       [8, 9]])

In [41]:
x[1:,1:4]

array([[6, 7, 8]])

- (3,8,13) 가져오기,  (5,6,7,8,9) 가져오기,  (1,2,3,6,7,8) 가져오기

In [42]:
y =x = np.arange(15).reshape(3,5)
print(y)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]


- (3,8,13) 가져오기,  (5,6,7,8,9) 가져오기,  (1,2,3,6,7,8) 가져오기

In [50]:
print(y[:,3:4])

[[ 3]
 [ 8]
 [13]]


In [51]:
print(y[1,:])

[5 6 7 8 9]


In [52]:
print(y[:2,1:4])

[[1 2 3]
 [6 7 8]]


In [56]:
arr8 = np.arange(1,13).reshape(3,4)
arr8

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

- arr8에서 5보다 작거나 같은 값만 추출

In [57]:
arr8[arr8 <= 5]

array([1, 2, 3, 4, 5])

- arr8에서 3의 배수만 추출하기

In [58]:
arr8[arr8 %3 == 0]

array([ 3,  6,  9, 12])

- x에서 2의 배수만 추출하기
- x에서 60이상의 수만 추출하기

In [63]:
x = np.random.randint(1,100, size=10)
x

array([45, 14, 59, 71, 86, 94, 83, 21, 89, 46])

In [60]:
x[x %2 == 0]

array([94, 70, 56, 74, 78, 80])

In [62]:
x[x >= 60]

array([99, 94, 83, 70, 73, 74, 78, 80])

- x에서 30보다 크고 70보다 작은수만 추출하기
- x에서 60보다 크거나 홀수인 수를 추출하기

In [64]:
x[(x > 30) &(x < 70)]

array([45, 59, 46])

In [65]:
x[(x > 60) | (x%2 != 0)]

array([45, 59, 71, 86, 94, 83, 21, 89])

- 예제) 2019년 7월 서울 기온 데이터
  - 기온이 25도를 넘는날 수?
  - 기온이 25도를 넘는 날의 평균 기온은?

In [66]:
temp = np.array(
        [23.9, 24.4, 24.1, 25.4, 27.6, 29.7,
         26.7, 25.1, 25.0, 22.7, 21.9, 23.6, 
         24.9, 25.9, 23.8, 24.7, 25.6, 26.9, 
         28.6, 28.0, 25.1, 26.7, 28.1, 26.5, 
         26.3, 25.9, 28.4, 26.1, 27.5, 28.1, 25.8])

In [67]:
len(temp)

31

In [78]:
temp_len = len(temp[temp > 25.0])
temp_len 

21

In [81]:
np.mean(temp[temp > 25.0])

26.857142857142858

## 정렬 : sort

#### 1. 1차원 정렬
     - 1 차원 정렬은 매우간단

In [83]:
arr = np.array([1,10,5,8,2,4,3,6,8,7,9])
arr

array([ 1, 10,  5,  8,  2,  4,  3,  6,  8,  7,  9])

In [88]:
np.sort(arr)                        # 오름차순 정렬

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [86]:
np.sort([1,10,5,8,2,4,3,6,8,7,9])

array([ 1,  2,  3,  4,  5,  6,  7,  8,  8,  9, 10])

In [87]:
np.sort(arr)[::-1]                    # 내림차순 정렬

array([10,  9,  8,  8,  7,  6,  5,  4,  3,  2,  1])

#### 2. N차원 정렬

In [ ]:
arr2d=np.array([[5,6,7,8],
              [4,3,2,1],
              [10,9,12,11]])

In [ ]:
arr2d.shape

#### 2-1 열 정렬 (왼쪽에서 오른쪽으로)

In [96]:
np.sort(arr2d,axis=1)

array([[ 5,  6,  7,  8],
       [ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [97]:
arr2d

array([[ 5,  6,  7,  8],
       [ 4,  3,  2,  1],
       [10,  9, 12, 11]])

#### 2-1 행 정렬 (위에서 아래로)

In [98]:
np.sort(arr2d,axis=0)

array([[ 4,  3,  2,  1],
       [ 5,  6,  7,  8],
       [10,  9, 12, 11]])

### y의 원소들의 평균,합,최대값,최솟값,분산,중앙값,표준편차 구하기

In [99]:
y =np.random.randint(100,size=(3,5))
print(y)

[[52 86 96 18 45]
 [75  3 63 69 60]
 [93 58 80 57 14]]


In [101]:
np.mean(y)        # 평균

57.93333333333333

In [102]:
y.sum()

869

In [103]:
y.max()

96

In [104]:
y.min()

3

In [105]:
y.var()            #분산

742.8622222222223

In [106]:
y.median()        # 중앙값은 직접 가져와야 한다.

AttributeError: 'numpy.ndarray' object has no attribute 'median'

In [108]:
np.median(y)      #중앙값

60.0

In [112]:
y.std()           #표준편차

27.25549893548497

In [113]:
np.std(y)

27.25549893548497