In [2]:
import numpy as np

## 10이 0개인 배열 출력

In [3]:
z = np.zeros(10)
print(z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## 5번째 숫자를 1로 변경

In [6]:
z[4] = 1
print(z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


## 10 이상 50 미만의 숫자가 들어가 있는 배열 생성

In [9]:
a= np.arange(10,51)
print(a)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


## 0~8  3x3배열 생성

In [10]:
z = np.arange(9).reshape(3,3)
print(z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


## 3x3x3 랜덤 정수

In [14]:
b = np.random.random((3,3,3))                       
print(b)

[[[0.30484002 0.93233698 0.77844134]
  [0.54378666 0.62265398 0.44166549]
  [0.3169282  0.31171742 0.25926021]]

 [[0.27913834 0.70165778 0.3258359 ]
  [0.64129377 0.23138199 0.68043329]
  [0.93998708 0.97108549 0.75208401]]

 [[0.95969303 0.74909486 0.32100794]
  [0.62352225 0.74694189 0.7293194 ]
  [0.26442685 0.06321    0.05897955]]]


## 전체 요소 개수 30개 배열 만들기
## 그 배열의 평군값 구하기

In [17]:
z =np.random.random(30)
print(z)

[0.64292862 0.52898333 0.97984025 0.61956218 0.08198289 0.27712881
 0.00477029 0.08100125 0.89610788 0.53267835 0.56524017 0.82168918
 0.23054942 0.64736751 0.82793055 0.7702996  0.65306618 0.31712786
 0.45512334 0.89559295 0.8149183  0.15250535 0.05305591 0.44819366
 0.5461692  0.87371184 0.43821322 0.36098238 0.90287411 0.11322713]


In [20]:
m= z.mean()
print(m)

0.5177607236638393


### 3명의 학생 평균 구하기

In [21]:
mid_score=[10,20,30]
final_score=[70,80,90]

In [22]:
total = mid_score+final_score
print(total)

[10, 20, 30, 70, 80, 90]


In [23]:
mid_score = np.array([10,20,30])
final_scor = np.array([70,80,90])

In [27]:
total = mid_score+final_score

In [28]:
total

array([ 80, 100, 120])

In [31]:
print("시험 성적의 합계:",total)

시험 성적의 합계: [ 80 100 120]


In [33]:
print("시험 성적의 평균:",total/2)

시험 성적의 평균: [40. 50. 60.]


### array_a = [1 2 3 4 5 6 7 8 9]
### array_b = [1 2 3 4 5 6 7 8 9]
### array_c = [0 2 3 4 6 8 ]
### array_c의 shape, ndim, dtype. size 출력

In [38]:
array_a = np.array ([1 ,2, 3, 4, 5, 6, 7, 8, 9])
print(array_a)

[1 2 3 4 5 6 7 8 9]


In [40]:
array_b = np.array (range(10))
print(array_b)

[0 1 2 3 4 5 6 7 8 9]


In [42]:
array_c = np.arange(0,10,2)
print(array_c)

[0 2 4 6 8]


In [45]:
array_c.itemsize      #배열내 원소크기

4

In [46]:
array_c.shape

(5,)

In [49]:
array_c.ndim         # 배열 차원 확인

1

### 월급 올리기

In [50]:
salary = np.array([220,250,230])

In [51]:
salary = salary + 100

In [52]:
salary

array([320, 350, 330])

In [54]:
salary = salary * 2
salary

array([1280, 1400, 1320])

### 선수들 몸무게,키

In [55]:
players = [[170,76.4],[183,86.2],[171,73.5],[176,80.1]]

In [57]:
np_players = np.array(players)
np_players

array([[170. ,  76.4],
       [183. ,  86.2],
       [171. ,  73.5],
       [176. ,  80.1]])

In [65]:
print('몸무게가 80 이상인 선수의 정보',np_players[np_players[:,1] >= 80.0])

몸무게가 80 이상인 선수의 정보 [[183.   86.2]
 [176.   80.1]]


In [66]:
print('키가 180 이상인 선수의 정보',np_players[np_players[:,0] >= 180.0])i

키가 180 이상인 선수의 정보 [[183.   86.2]]


In [124]:
import numpy as np

In [125]:
revenue_in_yen=[320,240,350,120,180,430,510,210,220,320,320,170,150,340,230,320,150,490,670,100,100,230,200,300,160,180,190,170,280,300]

In [126]:
yen_array= np.array(revenue_in_yen)
yen_array

array([320, 240, 350, 120, 180, 430, 510, 210, 220, 320, 320, 170, 150,
       340, 230, 320, 150, 490, 670, 100, 100, 230, 200, 300, 160, 180,
       190, 170, 280, 300])

In [127]:
yen_array.size

30

In [128]:
won_array = yen_array * 9.7

In [129]:
won_array

array([3104., 2328., 3395., 1164., 1746., 4171., 4947., 2037., 2134.,
       3104., 3104., 1649., 1455., 3298., 2231., 3104., 1455., 4753.,
       6499.,  970.,  970., 2231., 1940., 2910., 1552., 1746., 1843.,
       1649., 2716., 2910.])

In [130]:
revenue_in_doll=[32,24,35,12,18,43,51,21,22,32,32,17,15,34,23,32,15,49,67,10,10,23,20,30,16,18,19,17,28,30]

In [131]:
doll_array= np.array(revenue_in_doll)
doll_array

array([32, 24, 35, 12, 18, 43, 51, 21, 22, 32, 32, 17, 15, 34, 23, 32, 15,
       49, 67, 10, 10, 23, 20, 30, 16, 18, 19, 17, 28, 30])

In [132]:
doll_array = doll_array * 1391

In [133]:
doll_array

array([44512, 33384, 48685, 16692, 25038, 59813, 70941, 29211, 30602,
       44512, 44512, 23647, 20865, 47294, 31993, 44512, 20865, 68159,
       93197, 13910, 13910, 31993, 27820, 41730, 22256, 25038, 26429,
       23647, 38948, 41730])

In [138]:
won_array = yen_array*9.7 + doll_array*139

In [139]:
won_array

array([ 6190272.,  4642704.,  6770610.,  2321352.,  3482028.,  8318178.,
        9865746.,  4062366.,  4255812.,  6190272.,  6190272.,  3288582.,
        2901690.,  6577164.,  4449258.,  6190272.,  2901690.,  9478854.,
       12960882.,  1934460.,  1934460.,  4449258.,  3868920.,  5803380.,
        3095136.,  3482028.,  3675474.,  3288582.,  5416488.,  5803380.])

In [140]:
won_array.astype("int64")

array([ 6190272,  4642704,  6770610,  2321352,  3482028,  8318178,
        9865746,  4062366,  4255812,  6190272,  6190272,  3288582,
        2901690,  6577164,  4449258,  6190272,  2901690,  9478854,
       12960882,  1934460,  1934460,  4449258,  3868920,  5803380,
        3095136,  3482028,  3675474,  3288582,  5416488,  5803380],
      dtype=int64)

In [144]:
new_array = won_array*100

In [146]:
new_array

array([6.1902720e+08, 4.6427040e+08, 6.7706100e+08, 2.3213520e+08,
       3.4820280e+08, 8.3181780e+08, 9.8657460e+08, 4.0623660e+08,
       4.2558120e+08, 6.1902720e+08, 6.1902720e+08, 3.2885820e+08,
       2.9016900e+08, 6.5771640e+08, 4.4492580e+08, 6.1902720e+08,
       2.9016900e+08, 9.4788540e+08, 1.2960882e+09, 1.9344600e+08,
       1.9344600e+08, 4.4492580e+08, 3.8689200e+08, 5.8033800e+08,
       3.0951360e+08, 3.4820280e+08, 3.6754740e+08, 3.2885820e+08,
       5.4164880e+08, 5.8033800e+08])

## won_array에서 수익이 50,000 이하인 날을 뽑아봅시다( 조건문 사용)

In [147]:
sad_days = won_array[won_array <= 50000]

In [148]:
sad_days

array([], dtype=float64)