### 1. 목적
- iris 데이터를 활용하여 그리드서치를 적용

In [4]:
import warnings
warnings.filterwarnings('ignore')

In [5]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC

### 2. 데이터 수집

In [6]:
iris = load_iris()

In [7]:
x = iris.data
y = iris.target

### 3. 데이터 전처리

In [34]:
# train, test 데이터를 나누지 않을 경우
# 스케일러
# 학습
# 데이터 변환
scaler = StandardScaler()
scaler.fit(x)
x_scaled = scaler.transform(x)

In [38]:
scaler = StandardScaler()
x_scaled = scaler.fit_transform(x)

In [40]:
#x_train, x_test, y_train, x_test = train_test_split(x,y,random_state=0)

#scaler = StandardScaler(x_train)
#scaler.fit(x_train)
#x_train_scaled = scaler.transform(x_train)
#x_test_scaled = scaler.transform(x_test)

In [41]:
# scaler = StandardScaler(x_train)
# x_train_scaled  = scaler.fit.transform(x_train)
# x_test_scaled = scaler.transform(x_test)

In [53]:
x_train, x_test, y_train, y_test = train_test_split(x,y,random_state=0)

### 4. EDA 

### 5~7. 모델링(모델선택, 학습, 평가)

In [54]:
#knn
from sklearn.neighbors import KNeighborsClassifier

param_knn = {'n_neighbors' : range(1,10)}

In [55]:
knn = GridSearchCV(KNeighborsClassifier(), param_knn, cv=5)

In [56]:
knn.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': range(1, 10)})

In [57]:
print('최적의 파라미터 :', knn.best_params_)
print('최고 교차 검증 점수 :', knn.best_score_)
print('최고 성능 모델 :', knn.best_estimator_)

최적의 파라미터 : {'n_neighbors': 6}
최고 교차 검증 점수 : 0.9640316205533598
최고 성능 모델 : KNeighborsClassifier(n_neighbors=6)


In [58]:
knn.predict(x_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [59]:
knn.score(x_test, y_test)

0.9736842105263158

### decision tree

In [80]:
param_dt = {'max_depth' :range(1,10),
           'max_leaf_nodes': [1,2,3,4,5,6,7,8,9,10],
            'min_samples_leaf' : range(1,10)}

In [81]:
# 그리드 서치 모델 적용
dt = GridSearchCV(DecisionTreeClassifier(), param_dt, cv=5)

In [82]:
# 학습
dt.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(),
             param_grid={'max_depth': range(1, 10),
                         'max_leaf_nodes': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
                         'min_samples_leaf': range(1, 10)})

In [83]:
# 최적의 파라미터 
# 최고 교차 검증 점수
# 최고 성능 모델 - 을 print로 뽑아보기
print('최적의 파라미터 :', dt.best_params_)
print('최고 교차 검증 점수 :', dt.best_score_)
print('최고 성능 모델 :', dt.best_estimator_)

최적의 파라미터 : {'max_depth': 4, 'max_leaf_nodes': 5, 'min_samples_leaf': 2}
최고 교차 검증 점수 : 0.9731225296442687
최고 성능 모델 : DecisionTreeClassifier(max_depth=4, max_leaf_nodes=5, min_samples_leaf=2)


In [84]:
# 예측
dt.predict(x_test)

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 1, 2, 1, 0, 2])

In [85]:
# 스코어
dt.score(x_test, y_test)

0.9473684210526315

### SVM

In [104]:
# 파라미터 딕셔너리 만들기
param_svc = {'C':[0.001,0.01,0.1,5,10,25,50,100], 
             'gamma':[0.001,0.01,0.1,5,10,25,50,100], 
             'kernel':['poly','linear','rbf']}

In [105]:
# svc 모델 선언
svc = GridSearchCV(SVC(),param_svc, cv=5)

In [106]:
# 모델 학습
svc.fit(x_train, y_train)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [0.001, 0.01, 0.1, 5, 10, 25, 50, 100],
                         'gamma': [0.001, 0.01, 0.1, 5, 10, 25, 50, 100],
                         'kernel': ['poly', 'linear', 'rbf']})

In [107]:
# 최적의 파라미터
# 최고 교차 검증 점수
# 최고 성능 모델 - 을 print로 뽑아보기
print('최적의 파라미터 :', svc.best_params_)
print('최고 교차 검증 점수 :', svc.best_score_)
print('최고 성능 모델 :', svc.best_estimator_)

최적의 파라미터 : {'C': 0.1, 'gamma': 0.1, 'kernel': 'poly'}
최고 교차 검증 점수 : 0.9731225296442687
최고 성능 모델 : SVC(C=0.1, gamma=0.1, kernel='poly')


In [110]:
# 예측
pred = svc.predict(x_test)
pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2])

In [112]:
# 스코어
svc.score(x_test, y_test)

0.9736842105263158